style(sysupdate): added visual markers to distinguish update sections

diff --git a/bash/sysupdate b/bash/sysupdate
--- a/bash/sysupdate
+++ b/bash/sysupdate
@@ -89,31 +89,44 @@ function main() {
 	sudo -v
 	while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
 
-	printf "\n\e[1;34mStarting pacman package update...\e[0m\n\n"
+	printf " ➤ \e[1;34mStarting pacman package update...\e[0m\n"
 	if ! sudo pacman -Syu --noconfirm; then
 		printf "%b Failed to update system packages.\n" "$FORMAT_ERROR" >&2
+	else
+		printf "%b System packages updated successfully.\n" "$FORMAT_SUCCESS"
 	fi
 
-	printf "\n\e[1;34mStarting AUR package update...\e[0m\n\n"
+	printf " ➤ \e[1;34mStarting AUR package update...\e[0m\n"
 	if ! yay -Sua --noconfirm; then
 		printf "%b Failed to update AUR packages.\n" "$FORMAT_ERROR" >&2
+	else
+		printf "%b AUR packages updated successfully.\n" "$FORMAT_SUCCESS"
 	fi
 
-	printf "\n\e[1;34mChecking for Discord updates...\e[0m\n\n"
+	printf " ➤ \e[1;34mChecking for Discord updates...\e[0m\n"
 	if grep -q "\[ALPM\] upgraded discord" /var/log/pacman.log | grep "$(date +%Y-%m-%d)"; then
 		sh -c "$(curl -sS https://raw.githubusercontent.com/Vendicated/VencordInstaller/main/install.sh)"
+		printf "%b Discord hooks/Vencord updated.\n" "$FORMAT_SUCCESS"
+	else
+		printf "No Discord update detected.\n"
 	fi
 
-	printf "\n\e[1;34mUpdating Yazi plugins...\e[0m\n\n"
+	printf " ➤ \e[1;34mUpdating Yazi plugins...\e[0m\n"
 	if ! ya pkg upgrade; then
 		printf "%b Failed to update Yazi plugins.\n" "$FORMAT_ERROR" >&2
+	else
+		printf "%b Yazi plugins updated successfully.\n" "$FORMAT_SUCCESS"
 	fi
 
-	printf "\n\e[1;34mUpdating drxutils...\e[0m\n\n"
-	drxutilsUpdate
+	printf " ➤ \e[1;34mUpdating drxutils...\e[0m\n"
+	if drxutilsUpdate; then
+		printf "%b drxutils updated successfully.\n" "$FORMAT_SUCCESS"
+	else
+		printf "%b Failed to update drxutils.\n" "$FORMAT_ERROR" >&2
+	fi
 
 	local cacheSize=0
-	cacheSize=$(du -sm "$CACHE_ROUTE" | cut -f1)
+	cacheSize=$(du -sm "$CACHE_ROUTE" 2>/dev/null | cut -f1)
 	if [ "$cacheSize" -gt 8192 ]; then
 		local excludeArgs=()
 		for item in "${CACHE_WHITELIST[@]}"; do
@@ -125,8 +138,8 @@ function main() {
 	fi
 
 	local trashSize=0
-	trashSize=$(du -sm "$TRASH_ROUTE" | cut -f1)
-	if [ "$trashSize" -gt 32768 ]; then
+	trashSize=$(du -sm "$TRASH_ROUTE" 2>/dev/null | cut -f1)
+	if [ -n "$trashSize" ] && [ "$trashSize" -gt 32768 ]; then
 		sudo rm -rf "${TRASH_ROUTE:?}"/*
 		printf "%b Trash of size %sMB cleared successfully.\n" "$FORMAT_SUCCESS" "$trashSize"
 	fi
